language: rust
sudo: required
rust:
- stable
- beta
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo doc
after_success:
- travis-cargo --only nightly doc-upload
env:
  global:
  - secure: JVppvqlK5W5Iapee3gtdgF6hYpUcIQM0FvAP1RQx7ti7gpHEdHNkimgCASzXBCkuV7xJXBwY1nTV+5vJODI/B5F0O3e0CRwRKcBD1pWbZRj9Zodp1CGDEoOC1AV39pIeMRG8h5cPpz0268AzIP4OaFX9F40ZR0hoe2kx3kHMWSRlq8IJ7aTMLGt7Gz2uAbx9SB41R/7G9A6c87LzzPj2abTPW4zdPg7TFc9/9bzAjNNxHGNeCKI6PyFnKbo6lO5t3cAHVlb48e3yBynLiePCodcvAAe0qYo43Bv54kPIxKawbl3kqyLl1PmLQQf92DUG3+meBxIpOPBDA85xEwyyv82ZEGtq6lvHCCGc1sZCiLQh8RZ1AQjMVUuRncLPZit03gB7plvY/dWbnCfV/1poj/YB8rdTBvqnATH1ZKDjA/7aTZYvMT/UC4J1BbUA0QRf4V617mbiRzZjZqQLXP3Ah8/xew0Re6L1WRWofY5bCsptHdEksSrmQjaJXQoovvvoNaEGRYJsAmJiGUoY1XtfZI3PHtkKRADoOu/6cEXjt5cTXHpLyVHLoHS0WwRPfqMDdVZQVCSRuUBvYhTXj5ZSzr242/kWLNhpM05r7Cv/v6acgRFLXDZqSMbikvoJt7lbYk8u/9PFRv1pYw2e0AaCwQOYi/6U10C3t9EW5A+dnIY=
  - secure: U3ss3xkszzrSUnscbrDadFfARElQdjYng4DklaLKzsVS/E2o+bC6+lq5262sy0T/8KX87VzaiQPbitG3h70IDHVuqaE5SUlUWTt80ONmLoREv+TRH3aBWJuQdrB9WOwQWNy8j6E6HE/DZyMrfkitFYSVSzmS6vjl2tR/WHCBd90o1+CFkmE+ipSdVBE1EHwIznqI/vk7KbsduyoE5TYV3Tpg//TmqsINhuWZOCvZ5B0hHf7ZIcmbzjKSQvAaV3boxM1cxynU8Ijp0pyLwv/abXKRc+IzCkznhmVkZQ+CEca/+MpX6vRct1pZSSLYbUfDL3fTj4fGwHRb7rWF8000i9PCsw6zW3cv3zk+zf+/9H5jqeFm6Ds2KvqRloeL4vwFk93CNqXVezXvcJt4gDNXCu3NQMneuDzOqsJkh2cKKA2ouhsV67GGtmAH9NQU3CXgzDw4cshQS7QQz0qc0uvqLY7gINQm1IiYMpar1g7/3z3nwPvpMcmPYLkLYCAfPpvexe41i+y9hQGXhdAo6CW08LtR2wpo0lPha9VXQyVOkbXe04X//2PaB9rTUOFy/blVUBtqaYMVLyJd1UsCbqrHk5X0pj7Ta2t/0T9Vh08eqa+f5BKUMYql2D5RtJ0hKznARUMW1wyztyqELkUMv3E9OKKTYl68sNRqT+PX0u4sQMc=
